name: dmk
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Adding the assets section to include all image assets
  assets:
    - assets/images/contact_banner.jpg
    - assets/images/banner1.jpg
    - assets/images/banner2.jpg
    - assets/images/banner3.jpg
    - assets/images/garlic.jpg
    - assets/images/chinese_spinach.jpg
    - assets/images/green_onion.jpg
    - assets/images/apple.jpg
    - assets/images/broccoli.jpg
    - assets/images/carrot.jpg
    - assets/images/chilli.jpg
    - assets/images/cucumber.jpg
    - assets/images/ginger.jpg
    - assets/images/grape.jpg
    - assets/images/orange.jpg
    - assets/images/strawberry.jpg
    - assets/images/tomato.jpg
    
